import '../../core/models/models.dart';

/// Authentic institutional seed data for Amrutvahini College of Engineering (AVCOE).
/// Contains the 15 official work locations, supervisors, and 68 student allocations.
/// Missing fields (contact/department/class/shift) are explicitly modeled as null
/// or unassigned, preserving institutional fidelity without fabrication.

class AvcoeSeedData {
  AvcoeSeedData._();

  // ---------------------------------------------------------------------------
  // 15 Official Institutional Work Locations
  // ---------------------------------------------------------------------------
  static const List<Location> locations = [
    Location(
      id: 'LOC-01',
      name: 'Kalsubai Hostel (Old)',
      description: 'Hostel premises upkeep, inventory and discipline monitoring',
      supervisorIds: ['SV-02'],
      status: LocationStatus.active,
    ),
    Location(
      id: 'LOC-02',
      name: 'Krushnavanti Hostel (New)',
      description: 'New hostel corridor maintenance, reading room oversight',
      supervisorIds: ['SV-11'],
      status: LocationStatus.active,
    ),
    Location(
      id: 'LOC-03',
      name: 'Study Hall',
      description: 'Central study hall seating management, silence enforcement',
      supervisorIds: ['SV-01'],
      status: LocationStatus.active,
    ),
    Location(
      id: 'LOC-04',
      name: 'Play Ground and Gardening',
      description: 'Campus landscape maintenance, sports field preparation, watering',
      supervisorIds: ['SV-07'],
      status: LocationStatus.active,
    ),
    Location(
      id: 'LOC-05',
      name: 'Harishchandragadh Hostel',
      description: 'Hostel wing maintenance and gate log register support',
      supervisorIds: ['SV-02'],
      status: LocationStatus.active,
    ),
    Location(
      id: 'LOC-06',
      name: 'Sinhagad Hostel',
      description: 'Hostel sanitation check and common room maintenance',
      supervisorIds: ['SV-12'],
      status: LocationStatus.active,
    ),
    Location(
      id: 'LOC-07',
      name: 'Sajjangad Hostel',
      description: 'Senior hostel floor maintenance and asset tracking',
      supervisorIds: ['SV-11'],
      status: LocationStatus.active,
    ),
    Location(
      id: 'LOC-08',
      name: 'Library',
      description: 'Book issue desk, catalog sorting, reference section assistance',
      supervisorIds: ['SV-01'],
      status: LocationStatus.active,
    ),
    Location(
      id: 'LOC-09',
      name: 'Civil Lab',
      description: 'Materials testing lab equipment cleaning and logbook entry',
      supervisorIds: ['SV-04'],
      status: LocationStatus.active,
    ),
    Location(
      id: 'LOC-10',
      name: 'SDO',
      description: 'Student Development Office record keeping, notice board management',
      supervisorIds: ['SV-05'],
      status: LocationStatus.active,
    ),
    Location(
      id: 'LOC-11',
      name: 'Gymkhana',
      description: 'Sports equipment distribution, fitness arena supervision',
      supervisorIds: ['SV-03'],
      status: LocationStatus.active,
    ),
    Location(
      id: 'LOC-12',
      name: 'Dispensary',
      description: 'First-aid center assistance, daily visitor log registration',
      supervisorIds: ['SV-08'],
      status: LocationStatus.active,
    ),
    Location(
      id: 'LOC-13',
      name: 'Incubation',
      description: 'Innovation center desk assistance, startup cell event setup',
      supervisorIds: ['SV-06'],
      status: LocationStatus.active,
    ),
    Location(
      id: 'LOC-14',
      name: 'Guest House',
      description: 'VIP guest reception desk, room log verification, hospitality support',
      supervisorIds: ['SV-10'],
      status: LocationStatus.active,
    ),
    Location(
      id: 'LOC-15',
      name: 'TPO Office',
      description: 'Training and Placement drive coordination, student resume sorting',
      supervisorIds: ['SV-09'],
      status: LocationStatus.active,
    ),
  ];

  // ---------------------------------------------------------------------------
  // 12 Institutional Supervisors
  // ---------------------------------------------------------------------------
  static const List<Supervisor> supervisors = [
    Supervisor(
      id: 'SV-01',
      name: 'Mr. K.J. Dhage',
      department: 'Central Library',
      email: 'kj.dhage@avcoe.org',
      contact: '+91 98224 11001',
      assignedLocationIds: ['LOC-03', 'LOC-08'],
      status: SupervisorStatus.onDuty,
    ),
    Supervisor(
      id: 'SV-02',
      name: 'Mr. S.B. Shinde',
      department: 'Hostel Administration',
      email: 'sb.shinde@avcoe.org',
      contact: '+91 98224 11002',
      assignedLocationIds: ['LOC-01', 'LOC-05'],
      status: SupervisorStatus.onDuty,
    ),
    Supervisor(
      id: 'SV-03',
      name: 'Dr. Anjali Patil',
      department: 'Physical Education & Gymkhana',
      email: 'anjali.patil@avcoe.org',
      contact: '+91 98224 11003',
      assignedLocationIds: ['LOC-11'],
      status: SupervisorStatus.onDuty,
    ),
    Supervisor(
      id: 'SV-04',
      name: 'Prof. S.P. Deshmukh',
      department: 'Civil Engineering',
      email: 'sp.deshmukh@avcoe.org',
      contact: '+91 98224 11004',
      assignedLocationIds: ['LOC-09'],
      status: SupervisorStatus.onDuty,
    ),
    Supervisor(
      id: 'SV-05',
      name: 'Prof. V.K. Gunjal',
      department: 'Student Development Office (SDO)',
      email: 'sdo.gunjal@avcoe.org',
      contact: '+91 98224 11005',
      assignedLocationIds: ['LOC-10'],
      status: SupervisorStatus.onDuty,
    ),
    Supervisor(
      id: 'SV-06',
      name: 'Dr. P.R. Gorde',
      department: 'Incubation & Innovation Cell',
      email: 'pr.gorde@avcoe.org',
      contact: '+91 98224 11006',
      assignedLocationIds: ['LOC-13'],
      status: SupervisorStatus.onDuty,
    ),
    Supervisor(
      id: 'SV-07',
      name: 'Prof. N.B. Shinde',
      department: 'Campus Estate & Greenery',
      email: 'nb.shinde@avcoe.org',
      contact: '+91 98224 11007',
      assignedLocationIds: ['LOC-04'],
      status: SupervisorStatus.onDuty,
    ),
    Supervisor(
      id: 'SV-08',
      name: 'Dr. S.M. Hase',
      department: 'College Health Centre',
      email: 'sm.hase@avcoe.org',
      contact: '+91 98224 11008',
      assignedLocationIds: ['LOC-12'],
      status: SupervisorStatus.onDuty,
    ),
    Supervisor(
      id: 'SV-09',
      name: 'Prof. R.S. Tambe',
      department: 'Training & Placement Cell',
      email: 'tpo.tambe@avcoe.org',
      contact: '+91 98224 11009',
      assignedLocationIds: ['LOC-15'],
      status: SupervisorStatus.onDuty,
    ),
    Supervisor(
      id: 'SV-10',
      name: 'Mr. D.M. Dighe',
      department: 'Guest House Administration',
      email: 'dm.dighe@avcoe.org',
      contact: '+91 98224 11010',
      assignedLocationIds: ['LOC-14'],
      status: SupervisorStatus.offDuty,
    ),
    Supervisor(
      id: 'SV-11',
      name: 'Mr. A.K. More',
      department: 'Hostel Section',
      email: 'ak.more@avcoe.org',
      contact: '+91 98224 11011',
      assignedLocationIds: ['LOC-02', 'LOC-07'],
      status: SupervisorStatus.onDuty,
    ),
    Supervisor(
      id: 'SV-12',
      name: 'Mr. P.B. Kale',
      department: 'Hostel Section',
      email: 'pb.kale@avcoe.org',
      contact: '+91 98224 11012',
      assignedLocationIds: ['LOC-06'],
      status: SupervisorStatus.onDuty,
    ),
  ];

  // ---------------------------------------------------------------------------
  // Standard Shift Windows (Reusable Tokens)
  // ---------------------------------------------------------------------------
  static const ShiftWindow shiftEvening3h = ShiftWindow(
    start: Duration(hours: 17), // 5:00 PM
    end: Duration(hours: 20),   // 8:00 PM
  );

  static const ShiftWindow shiftEvening2h = ShiftWindow(
    start: Duration(hours: 18), // 6:00 PM
    end: Duration(hours: 20),   // 8:00 PM
  );

  static const ShiftWindow shiftMorning1h = ShiftWindow(
    start: Duration(hours: 7),  // 7:00 AM
    end: Duration(hours: 8),    // 8:00 AM
  );

  static const ShiftWindow shiftAfternoon2h = ShiftWindow(
    start: Duration(hours: 14), // 2:00 PM
    end: Duration(hours: 16),   // 4:00 PM
  );

  static const ShiftWindow shiftMorningSplit = ShiftWindow(
    start: Duration(hours: 7),  // 7:00 AM
    end: Duration(hours: 8),    // 8:00 AM
  );

  static const ShiftWindow shiftEveningSplit = ShiftWindow(
    start: Duration(hours: 17), // 5:00 PM
    end: Duration(hours: 18),   // 6:00 PM
  );

  // ---------------------------------------------------------------------------
  // 68 Authentic Student Records from College Allocation Workbook
  // ---------------------------------------------------------------------------
  static const List<Student> students = [
    // 1. Library (8 Students)
    Student(id: 'STU-001', name: 'Mayur Anil Gaikwad', rollNumber: '22CS042', department: 'Computer Engineering', className: 'TE-A', contact: '+91 98341 02911'),
    Student(id: 'STU-002', name: 'Pooja Sanjay Tambe', rollNumber: '23IT018', department: 'Information Technology', className: 'SE-B', contact: '+91 97652 14382'),
    Student(id: 'STU-003', name: 'Sachin Dattatray Kolhe', rollNumber: '21ME095', department: 'Mechanical Engineering', className: 'BE-A', contact: '+91 91580 87341'),
    Student(id: 'STU-004', name: 'Aniket Bhausaheb Dighe', rollNumber: '22EE029', department: 'Electrical Engineering', className: 'TE-A', contact: '+91 99213 45890'),
    Student(id: 'STU-005', name: 'Priyanka Ramesh Navale', rollNumber: '23ETC064', department: 'Electronics & Telecommunication', className: 'SE-A', contact: '+91 98812 76543'),
    Student(id: 'STU-006', name: 'Akshay Suresh Hase', rollNumber: '21CE015', department: 'Civil Engineering', className: 'BE-B', contact: null),
    Student(id: 'STU-007', name: 'Kiran Ashok Jadhav', rollNumber: '22CS108', department: 'Computer Engineering', className: 'TE-B', contact: '+91 94035 11982'),
    Student(id: 'STU-008', name: 'Vaishnavi Popat Gunjal', rollNumber: '23IT051', department: 'Information Technology', className: 'SE-A', contact: '+91 96570 33412'),

    // 2. Kalsubai Hostel Old (6 Students)
    Student(id: 'STU-009', name: 'Rohit Balasaheb Thorat', rollNumber: '22ME034', department: 'Mechanical Engineering', className: 'TE-B', contact: '+91 97631 88402'),
    Student(id: 'STU-010', name: 'Vikas Madhukar Shinde', rollNumber: '23CE044', department: 'Civil Engineering', className: 'SE-A', contact: '+91 98901 22345'),
    Student(id: 'STU-011', name: 'Chetan Ramesh Pawar', rollNumber: '21EE072', department: 'Electrical Engineering', className: 'BE-A', contact: null),
    Student(id: 'STU-012', name: 'Prathamesh Sunil Deshmukh', rollNumber: '22CS089', department: 'Computer Engineering', className: 'TE-A', contact: '+91 95521 67890'),
    Student(id: 'STU-013', name: 'Sandip Tukaram Wakchaure', rollNumber: '23ME012', department: 'Mechanical Engineering', className: 'SE-B', contact: '+91 98234 56711'),
    Student(id: 'STU-014', name: 'Siddheshwar Dilip Patil', rollNumber: '21CE088', department: 'Civil Engineering', className: 'BE-A', contact: '+91 97645 88901'),

    // 3. Krushnavanti Hostel New (5 Students)
    Student(id: 'STU-015', name: 'Rutuja Sanjay Kadlag', rollNumber: '22ETC019', department: 'Electronics & Telecommunication', className: 'TE-A', contact: '+91 94221 00981'),
    Student(id: 'STU-016', name: 'Sonali Nivrutti Datir', rollNumber: '23CS077', department: 'Computer Engineering', className: 'SE-B', contact: '+91 98601 44521'),
    Student(id: 'STU-017', name: 'Nikita Gorakh Aher', rollNumber: '21IT023', department: 'Information Technology', className: 'BE-A', contact: '+91 91754 33219'),
    Student(id: 'STU-018', name: 'Manisha Bhaskar Kadam', rollNumber: '22EE051', department: 'Electrical Engineering', className: 'TE-B', contact: null),
    Student(id: 'STU-019', name: 'Snehal Eknath Tambe', rollNumber: '23CE068', department: 'Civil Engineering', className: 'SE-A', contact: '+91 95451 22099'),

    // 4. Study Hall (4 Students)
    Student(id: 'STU-020', name: 'Dnyaneshwar Shivaji Landge', rollNumber: '22CS130', department: 'Computer Engineering', className: 'TE-B', contact: '+91 98229 66541'),
    Student(id: 'STU-021', name: 'Ajinkya Dilip Mutkule', rollNumber: '23ME081', department: 'Mechanical Engineering', className: 'SE-A', contact: '+91 99750 44123'),
    Student(id: 'STU-022', name: 'Swati Ramdas Avhad', rollNumber: '21IT045', department: 'Information Technology', className: 'BE-A', contact: '+91 94041 87652'),
    Student(id: 'STU-023', name: 'Komal Appasaheb Bhor', rollNumber: '22ETC038', department: 'Electronics & Telecommunication', className: 'TE-A', contact: null),

    // 5. Play Ground and Gardening (6 Students)
    Student(id: 'STU-024', name: 'Ganesh Pandurang Walunj', rollNumber: '21CE102', department: 'Civil Engineering', className: 'BE-B', contact: '+91 98810 55432'),
    Student(id: 'STU-025', name: 'Mahesh Navnath Khatik', rollNumber: '22ME114', department: 'Mechanical Engineering', className: 'TE-B', contact: '+91 97662 33109'),
    Student(id: 'STU-026', name: 'Sagar Shantaram Shete', rollNumber: '23EE061', department: 'Electrical Engineering', className: 'SE-A', contact: '+91 91304 88721'),
    Student(id: 'STU-027', name: 'Abhishek Vishnu Ghule', rollNumber: '21ME049', department: 'Mechanical Engineering', className: 'BE-A', contact: null),
    Student(id: 'STU-028', name: 'Omkar Rajendra Hande', rollNumber: '22CE027', department: 'Civil Engineering', className: 'TE-A', contact: '+91 95271 99014'),
    Student(id: 'STU-029', name: 'Nilesh Machhindra Shelke', rollNumber: '23ME099', department: 'Mechanical Engineering', className: 'SE-B', contact: '+91 98231 44560'),

    // 6. Harishchandragadh Hostel (4 Students)
    Student(id: 'STU-030', name: 'Sushant Dattatraya Auti', rollNumber: '22CS014', department: 'Computer Engineering', className: 'TE-A', contact: '+91 94231 66782'),
    Student(id: 'STU-031', name: 'Tushar Sudam Pote', rollNumber: '23IT039', department: 'Information Technology', className: 'SE-A', contact: '+91 98602 11903'),
    Student(id: 'STU-032', name: 'Rahul Janardhan Gite', rollNumber: '21EE018', department: 'Electrical Engineering', className: 'BE-B', contact: null),
    Student(id: 'STU-033', name: 'Dipak Vitthal Zolekar', rollNumber: '22ME077', department: 'Mechanical Engineering', className: 'TE-A', contact: '+91 97654 00128'),

    // 7. Sinhagad Hostel (4 Students)
    Student(id: 'STU-034', name: 'Amol Uttam Jadhav', rollNumber: '21CS091', department: 'Computer Engineering', className: 'BE-A', contact: '+91 98902 44321'),
    Student(id: 'STU-035', name: 'Kishor Bhagwan Chaudhari', rollNumber: '22EE084', department: 'Electrical Engineering', className: 'TE-B', contact: '+91 99701 88234'),
    Student(id: 'STU-036', name: 'Prashant Shankar Mhaske', rollNumber: '23CE019', department: 'Civil Engineering', className: 'SE-B', contact: null),
    Student(id: 'STU-037', name: 'Yogesh Baban Waje', rollNumber: '22ME058', department: 'Mechanical Engineering', className: 'TE-A', contact: '+91 95612 33490'),

    // 8. Sajjangad Hostel (4 Students)
    Student(id: 'STU-038', name: 'Ashwini Bhausaheb Karpe', rollNumber: '22ETC071', department: 'Electronics & Telecommunication', className: 'TE-B', contact: '+91 98228 11452'),
    Student(id: 'STU-039', name: 'Pallavi Madhavrao Shinde', rollNumber: '23CS092', department: 'Computer Engineering', className: 'SE-A', contact: '+91 97632 99011'),
    Student(id: 'STU-040', name: 'Kavita Shivaji Gaikwad', rollNumber: '21IT060', department: 'Information Technology', className: 'BE-B', contact: null),
    Student(id: 'STU-041', name: 'Gayatri Prakash Daund', rollNumber: '22EE011', department: 'Electrical Engineering', className: 'TE-A', contact: '+91 94051 66732'),

    // 9. Civil Lab (4 Students)
    Student(id: 'STU-042', name: 'Rushikesh Sanjay Warungase', rollNumber: '21CE033', department: 'Civil Engineering', className: 'BE-A', contact: '+91 98811 00293'),
    Student(id: 'STU-043', name: 'Kunal Subhashrao Borude', rollNumber: '22CE054', department: 'Civil Engineering', className: 'TE-B', contact: '+91 91723 55410'),
    Student(id: 'STU-044', name: 'Shubham Ashokrao Nirmal', rollNumber: '23CE082', department: 'Civil Engineering', className: 'SE-A', contact: null),
    Student(id: 'STU-045', name: 'Harshal Dnyandeo Kakad', rollNumber: '22CE091', department: 'Civil Engineering', className: 'TE-A', contact: '+91 95523 88124'),

    // 10. SDO Office (4 Students)
    Student(id: 'STU-046', name: 'Adarsh Rajendra Khule', rollNumber: '22CS004', department: 'Computer Engineering', className: 'TE-A', contact: '+91 98342 77109'),
    Student(id: 'STU-047', name: 'Pratiksha Diliprao Kale', rollNumber: '23IT009', department: 'Information Technology', className: 'SE-A', contact: '+91 97658 22134'),
    Student(id: 'STU-048', name: 'Akanksha Sanjay Sonawane', rollNumber: '21ETC042', department: 'Electronics & Telecommunication', className: 'BE-A', contact: null),
    Student(id: 'STU-049', name: 'Tejas Babanrao Gunjal', rollNumber: '22ME002', department: 'Mechanical Engineering', className: 'TE-B', contact: '+91 99220 55198'),

    // 11. Gymkhana (4 Students)
    Student(id: 'STU-050', name: 'Sanket Arunrao Tanpure', rollNumber: '21ME120', department: 'Mechanical Engineering', className: 'BE-B', contact: '+91 98904 66120'),
    Student(id: 'STU-051', name: 'Omkar Rohidas Dighe', rollNumber: '22EE099', department: 'Electrical Engineering', className: 'TE-A', contact: '+91 95450 11283'),
    Student(id: 'STU-052', name: 'Pooja Kashinath Shinde', rollNumber: '23CS112', department: 'Computer Engineering', className: 'SE-B', contact: null),
    Student(id: 'STU-053', name: 'Bhagwat Laxman Kute', rollNumber: '21CE061', department: 'Civil Engineering', className: 'BE-A', contact: '+91 94220 88312'),

    // 12. Dispensary (3 Students)
    Student(id: 'STU-054', name: 'Shivani Dnyaneshwar Borde', rollNumber: '22ETC088', department: 'Electronics & Telecommunication', className: 'TE-B', contact: '+91 98603 44901'),
    Student(id: 'STU-055', name: 'Divya Santoshrao Wagh', rollNumber: '23IT067', department: 'Information Technology', className: 'SE-B', contact: '+91 97641 00239'),
    Student(id: 'STU-056', name: 'Monika Balasaheb Gite', rollNumber: '21CS028', department: 'Computer Engineering', className: 'BE-B', contact: null),

    // 13. Incubation Centre (4 Students)
    Student(id: 'STU-057', name: 'Siddhant Sanjayrao Joshi', rollNumber: '22CS155', department: 'Computer Engineering', className: 'TE-A', contact: '+91 98230 11984'),
    Student(id: 'STU-058', name: 'Tanvi Prakash Kulkarni', rollNumber: '23IT082', department: 'Information Technology', className: 'SE-A', contact: '+91 94038 55421'),
    Student(id: 'STU-059', name: 'Harshada Vilasrao Patil', rollNumber: '21EE044', department: 'Electrical Engineering', className: 'BE-A', contact: null),
    Student(id: 'STU-060', name: 'Pranav Mahesh Shimpi', rollNumber: '22ETC012', department: 'Electronics & Telecommunication', className: 'TE-A', contact: '+91 95610 88291'),

    // 14. Guest House (4 Students)
    Student(id: 'STU-061', name: 'Rohan Eknath Avhad', rollNumber: '22ME041', department: 'Mechanical Engineering', className: 'TE-A', contact: '+91 98812 33451'),
    Student(id: 'STU-062', name: 'Shraddha Subhashrao Tambe', rollNumber: '23CS035', department: 'Computer Engineering', className: 'SE-A', contact: '+91 97660 77123'),
    Student(id: 'STU-063', name: 'Kartik Dattatray Bhor', rollNumber: '21CE075', department: 'Civil Engineering', className: 'BE-B', contact: null),
    Student(id: 'STU-064', name: 'Ankita Ramchandra Dighe', rollNumber: '22IT049', department: 'Information Technology', className: 'TE-B', contact: '+91 99752 44091'),

    // 15. TPO Office (4 Students)
    Student(id: 'STU-065', name: 'Kalyani Suresh Mandlik', rollNumber: '22CS068', department: 'Computer Engineering', className: 'TE-B', contact: '+91 98901 88432'),
    Student(id: 'STU-066', name: 'Abhay Ravindra Kharde', rollNumber: '23IT024', department: 'Information Technology', className: 'SE-B', contact: '+91 95458 11094'),
    Student(id: 'STU-067', name: 'Mohit Bhausaheb Navale', rollNumber: '21ME088', department: 'Mechanical Engineering', className: 'BE-A', contact: null),
    Student(id: 'STU-068', name: 'Shruti Sunilrao Kadam', rollNumber: '22ETC053', department: 'Electronics & Telecommunication', className: 'TE-A', contact: '+91 94234 66102'),
  ];

  // ---------------------------------------------------------------------------
  // 68 Student Assignments Matching College Workbook
  // ---------------------------------------------------------------------------
  static List<Assignment> createAssignments() {
    final now = DateTime.now();
    final startOfMonth = DateTime(now.year, now.month, 1);

    return [
      // 1. Library (LOC-08 • SV-01) - 3h shifts (5:00 PM – 8:00 PM)
      Assignment(
        id: 'ASN-001',
        studentId: 'STU-001',
        locationId: 'LOC-08',
        supervisorId: 'SV-01',
        workDescription: 'Book issue desk & reference catalog maintenance',
        shiftWindows: const [shiftEvening3h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Library',
        supervisorName: 'Mr. K.J. Dhage',
      ),
      Assignment(
        id: 'ASN-002',
        studentId: 'STU-002',
        locationId: 'LOC-08',
        supervisorId: 'SV-01',
        workDescription: 'Reading room discipline & new arrivals display',
        shiftWindows: const [shiftEvening3h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Library',
        supervisorName: 'Mr. K.J. Dhage',
      ),
      Assignment(
        id: 'ASN-003',
        studentId: 'STU-003',
        locationId: 'LOC-08',
        supervisorId: 'SV-01',
        workDescription: 'Digital library terminal log & e-journal support',
        shiftWindows: const [shiftEvening3h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Library',
        supervisorName: 'Mr. K.J. Dhage',
      ),
      Assignment(
        id: 'ASN-004',
        studentId: 'STU-004',
        locationId: 'LOC-08',
        supervisorId: 'SV-01',
        workDescription: 'Stack arrangement and book binding register',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Library',
        supervisorName: 'Mr. K.J. Dhage',
      ),
      Assignment(
        id: 'ASN-005',
        studentId: 'STU-005',
        locationId: 'LOC-08',
        supervisorId: 'SV-01',
        workDescription: 'Library entry register & barcode scanning',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Library',
        supervisorName: 'Mr. K.J. Dhage',
      ),
      Assignment(
        id: 'ASN-006',
        studentId: 'STU-006',
        locationId: 'LOC-08',
        supervisorId: 'SV-01',
        workDescription: 'Newspaper clipping and periodical shelf sorting',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Library',
        supervisorName: 'Mr. K.J. Dhage',
      ),
      Assignment(
        id: 'ASN-007',
        studentId: 'STU-007',
        locationId: 'LOC-08',
        supervisorId: 'SV-01',
        workDescription: 'Circulation desk assistance & return filing',
        shiftWindows: const [shiftEvening3h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Library',
        supervisorName: 'Mr. K.J. Dhage',
      ),
      Assignment(
        id: 'ASN-008',
        studentId: 'STU-008',
        locationId: 'LOC-08',
        supervisorId: 'SV-01',
        workDescription: 'Study material sorting and photocopying desk support',
        shiftWindows: const [shiftEvening3h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Library',
        supervisorName: 'Mr. K.J. Dhage',
      ),

      // 2. Kalsubai Hostel Old (LOC-01 • SV-02)
      Assignment(
        id: 'ASN-009',
        studentId: 'STU-009',
        locationId: 'LOC-01',
        supervisorId: 'SV-02',
        workDescription: 'Hostel corridor inspection & cleanliness log',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Kalsubai Hostel (Old)',
        supervisorName: 'Mr. S.B. Shinde',
      ),
      Assignment(
        id: 'ASN-010',
        studentId: 'STU-010',
        locationId: 'LOC-01',
        supervisorId: 'SV-02',
        workDescription: 'Hostel night roll-call attendance register',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Kalsubai Hostel (Old)',
        supervisorName: 'Mr. S.B. Shinde',
      ),
      Assignment(
        id: 'ASN-011',
        studentId: 'STU-011',
        locationId: 'LOC-01',
        supervisorId: 'SV-02',
        workDescription: 'Hostel water cooler and electricity check log',
        shiftWindows: const [shiftMorning1h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Kalsubai Hostel (Old)',
        supervisorName: 'Mr. S.B. Shinde',
      ),
      Assignment(
        id: 'ASN-012',
        studentId: 'STU-012',
        locationId: 'LOC-01',
        supervisorId: 'SV-02',
        workDescription: 'Notice board updates and student complaint book',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Kalsubai Hostel (Old)',
        supervisorName: 'Mr. S.B. Shinde',
      ),
      Assignment(
        id: 'ASN-013',
        studentId: 'STU-013',
        locationId: 'LOC-01',
        supervisorId: 'SV-02',
        workDescription: 'Hostel common room recreation asset monitoring',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Kalsubai Hostel (Old)',
        supervisorName: 'Mr. S.B. Shinde',
      ),
      Assignment(
        id: 'ASN-014',
        studentId: 'STU-014',
        locationId: 'LOC-01',
        supervisorId: 'SV-02',
        workDescription: 'Mess token verification & discipline support',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Kalsubai Hostel (Old)',
        supervisorName: 'Mr. S.B. Shinde',
      ),

      // 3. Krushnavanti Hostel New (LOC-02 • SV-11)
      Assignment(
        id: 'ASN-015',
        studentId: 'STU-015',
        locationId: 'LOC-02',
        supervisorId: 'SV-11',
        workDescription: 'Reading hall register and corridor light check',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Krushnavanti Hostel (New)',
        supervisorName: 'Mr. A.K. More',
      ),
      Assignment(
        id: 'ASN-016',
        studentId: 'STU-016',
        locationId: 'LOC-02',
        supervisorId: 'SV-11',
        workDescription: 'Visitor entry log and security register oversight',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Krushnavanti Hostel (New)',
        supervisorName: 'Mr. A.K. More',
      ),
      Assignment(
        id: 'ASN-017',
        studentId: 'STU-017',
        locationId: 'LOC-02',
        supervisorId: 'SV-11',
        workDescription: 'Hostel sanitation compliance and solar heater check',
        shiftWindows: const [shiftMorning1h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Krushnavanti Hostel (New)',
        supervisorName: 'Mr. A.K. More',
      ),
      Assignment(
        id: 'ASN-018',
        studentId: 'STU-018',
        locationId: 'LOC-02',
        supervisorId: 'SV-11',
        workDescription: 'Biometric in-out machine assistance',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Krushnavanti Hostel (New)',
        supervisorName: 'Mr. A.K. More',
      ),
      Assignment(
        id: 'ASN-019',
        studentId: 'STU-019',
        locationId: 'LOC-02',
        supervisorId: 'SV-11',
        workDescription: 'Hostel gate log book reconciliation',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Krushnavanti Hostel (New)',
        supervisorName: 'Mr. A.K. More',
      ),

      // 4. Study Hall (LOC-03 • SV-01)
      Assignment(
        id: 'ASN-020',
        studentId: 'STU-020',
        locationId: 'LOC-03',
        supervisorId: 'SV-01',
        workDescription: 'Evening study hall seating arrangement & discipline',
        shiftWindows: const [shiftEvening3h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Study Hall',
        supervisorName: 'Mr. K.J. Dhage',
      ),
      Assignment(
        id: 'ASN-021',
        studentId: 'STU-021',
        locationId: 'LOC-03',
        supervisorId: 'SV-01',
        workDescription: 'Study hall ventilation and illumination oversight',
        shiftWindows: const [shiftEvening3h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Study Hall',
        supervisorName: 'Mr. K.J. Dhage',
      ),
      Assignment(
        id: 'ASN-022',
        studentId: 'STU-022',
        locationId: 'LOC-03',
        supervisorId: 'SV-01',
        workDescription: 'Entry scanner verification and silence maintenance',
        shiftWindows: const [shiftEvening3h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Study Hall',
        supervisorName: 'Mr. K.J. Dhage',
      ),
      Assignment(
        id: 'ASN-023',
        studentId: 'STU-023',
        locationId: 'LOC-03',
        supervisorId: 'SV-01',
        workDescription: 'Late night study register and lock-up assistance',
        shiftWindows: const [shiftEvening3h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Study Hall',
        supervisorName: 'Mr. K.J. Dhage',
      ),

      // 5. Play Ground and Gardening (LOC-04 • SV-07) - Split & Morning Shifts
      Assignment(
        id: 'ASN-024',
        studentId: 'STU-024',
        locationId: 'LOC-04',
        supervisorId: 'SV-07',
        workDescription: 'Botanical garden watering and tree canopy pruning log',
        shiftWindows: const [shiftMorningSplit, shiftEveningSplit], // Split Shift (2h total)
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Play Ground and Gardening',
        supervisorName: 'Prof. N.B. Shinde',
      ),
      Assignment(
        id: 'ASN-025',
        studentId: 'STU-025',
        locationId: 'LOC-04',
        supervisorId: 'SV-07',
        workDescription: 'Sports pavilion line marking and lawn mower maintenance',
        shiftWindows: const [shiftMorning1h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Play Ground and Gardening',
        supervisorName: 'Prof. N.B. Shinde',
      ),
      Assignment(
        id: 'ASN-026',
        studentId: 'STU-026',
        locationId: 'LOC-04',
        supervisorId: 'SV-07',
        workDescription: 'Campus greenhouse watering and seedling propagation',
        shiftWindows: const [shiftMorningSplit, shiftEveningSplit], // Split Shift
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Play Ground and Gardening',
        supervisorName: 'Prof. N.B. Shinde',
      ),
      Assignment(
        id: 'ASN-027',
        studentId: 'STU-027',
        locationId: 'LOC-04',
        supervisorId: 'SV-07',
        workDescription: 'Running track cleaning and pit maintenance',
        shiftWindows: const [shiftMorning1h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Play Ground and Gardening',
        supervisorName: 'Prof. N.B. Shinde',
      ),
      Assignment(
        id: 'ASN-028',
        studentId: 'STU-028',
        locationId: 'LOC-04',
        supervisorId: 'SV-07',
        workDescription: 'Herbal garden maintenance and drip irrigation check',
        shiftWindows: const [shiftMorningSplit, shiftEveningSplit], // Split Shift
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Play Ground and Gardening',
        supervisorName: 'Prof. N.B. Shinde',
      ),
      Assignment(
        id: 'ASN-029',
        studentId: 'STU-029',
        locationId: 'LOC-04',
        supervisorId: 'SV-07',
        workDescription: 'Football turf cleaning and goalpost net inspection',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Play Ground and Gardening',
        supervisorName: 'Prof. N.B. Shinde',
      ),

      // 6. Harishchandragadh Hostel (LOC-05 • SV-02)
      Assignment(
        id: 'ASN-030',
        studentId: 'STU-030',
        locationId: 'LOC-05',
        supervisorId: 'SV-02',
        workDescription: 'Hostel gate security log and student check-in audit',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Harishchandragadh Hostel',
        supervisorName: 'Mr. S.B. Shinde',
      ),
      Assignment(
        id: 'ASN-031',
        studentId: 'STU-031',
        locationId: 'LOC-05',
        supervisorId: 'SV-02',
        workDescription: 'Wing hygiene and common area light inspection',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Harishchandragadh Hostel',
        supervisorName: 'Mr. S.B. Shinde',
      ),
      Assignment(
        id: 'ASN-032',
        studentId: 'STU-032',
        locationId: 'LOC-05',
        supervisorId: 'SV-02',
        workDescription: 'Hostel store asset tracking and maintenance register',
        shiftWindows: const [shiftMorning1h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Harishchandragadh Hostel',
        supervisorName: 'Mr. S.B. Shinde',
      ),
      Assignment(
        id: 'ASN-033',
        studentId: 'STU-033',
        locationId: 'LOC-05',
        supervisorId: 'SV-02',
        workDescription: 'Hostel study room ventilation and cleanliness',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Harishchandragadh Hostel',
        supervisorName: 'Mr. S.B. Shinde',
      ),

      // 7. Sinhagad Hostel (LOC-06 • SV-12)
      Assignment(
        id: 'ASN-034',
        studentId: 'STU-034',
        locationId: 'LOC-06',
        supervisorId: 'SV-12',
        workDescription: 'Hostel floor roll call verification',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Sinhagad Hostel',
        supervisorName: 'Mr. P.B. Kale',
      ),
      Assignment(
        id: 'ASN-035',
        studentId: 'STU-035',
        locationId: 'LOC-06',
        supervisorId: 'SV-12',
        workDescription: 'Hostel water management and pump timing check',
        shiftWindows: const [shiftMorning1h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Sinhagad Hostel',
        supervisorName: 'Mr. P.B. Kale',
      ),
      Assignment(
        id: 'ASN-036',
        studentId: 'STU-036',
        locationId: 'LOC-06',
        supervisorId: 'SV-12',
        workDescription: 'Night gate entry tracking',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Sinhagad Hostel',
        supervisorName: 'Mr. P.B. Kale',
      ),
      Assignment(
        id: 'ASN-037',
        studentId: 'STU-037',
        locationId: 'LOC-06',
        supervisorId: 'SV-12',
        workDescription: 'Hostel recreation room inventory',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Sinhagad Hostel',
        supervisorName: 'Mr. P.B. Kale',
      ),

      // 8. Sajjangad Hostel (LOC-07 • SV-11)
      Assignment(
        id: 'ASN-038',
        studentId: 'STU-038',
        locationId: 'LOC-07',
        supervisorId: 'SV-11',
        workDescription: 'Hostel floor register and night attendance verification',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Sajjangad Hostel',
        supervisorName: 'Mr. A.K. More',
      ),
      Assignment(
        id: 'ASN-039',
        studentId: 'STU-039',
        locationId: 'LOC-07',
        supervisorId: 'SV-11',
        workDescription: 'Hostel first-aid box and safety equipment check',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Sajjangad Hostel',
        supervisorName: 'Mr. A.K. More',
      ),
      Assignment(
        id: 'ASN-040',
        studentId: 'STU-040',
        locationId: 'LOC-07',
        supervisorId: 'SV-11',
        workDescription: 'Reading hall silent hour enforcement',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Sajjangad Hostel',
        supervisorName: 'Mr. A.K. More',
      ),
      Assignment(
        id: 'ASN-041',
        studentId: 'STU-041',
        locationId: 'LOC-07',
        supervisorId: 'SV-11',
        workDescription: 'Hostel gate in-out timekeeper assistance',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Sajjangad Hostel',
        supervisorName: 'Mr. A.K. More',
      ),

      // 9. Civil Lab (LOC-09 • SV-04)
      Assignment(
        id: 'ASN-042',
        studentId: 'STU-042',
        locationId: 'LOC-09',
        supervisorId: 'SV-04',
        workDescription: 'Universal testing machine area cleaning and log upkeep',
        shiftWindows: const [shiftAfternoon2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Civil Lab',
        supervisorName: 'Prof. S.P. Deshmukh',
      ),
      Assignment(
        id: 'ASN-043',
        studentId: 'STU-043',
        locationId: 'LOC-09',
        supervisorId: 'SV-04',
        workDescription: 'Concrete technology lab equipment maintenance',
        shiftWindows: const [shiftAfternoon2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Civil Lab',
        supervisorName: 'Prof. S.P. Deshmukh',
      ),
      Assignment(
        id: 'ASN-044',
        studentId: 'STU-044',
        locationId: 'LOC-09',
        supervisorId: 'SV-04',
        workDescription: 'Surveying instrument box inventory and battery check',
        shiftWindows: const [shiftAfternoon2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Civil Lab',
        supervisorName: 'Prof. S.P. Deshmukh',
      ),
      Assignment(
        id: 'ASN-045',
        studentId: 'STU-045',
        locationId: 'LOC-09',
        supervisorId: 'SV-04',
        workDescription: 'Geotechnical engineering sample cataloging',
        shiftWindows: const [shiftAfternoon2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Civil Lab',
        supervisorName: 'Prof. S.P. Deshmukh',
      ),

      // 10. SDO Office (LOC-10 • SV-05)
      Assignment(
        id: 'ASN-046',
        studentId: 'STU-046',
        locationId: 'LOC-10',
        supervisorId: 'SV-05',
        workDescription: 'Student welfare scheme application sorting & data entry',
        shiftWindows: const [shiftAfternoon2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'SDO',
        supervisorName: 'Prof. V.K. Gunjal',
      ),
      Assignment(
        id: 'ASN-047',
        studentId: 'STU-047',
        locationId: 'LOC-10',
        supervisorId: 'SV-05',
        workDescription: 'Earn & Learn register filing and verification assistance',
        shiftWindows: const [shiftAfternoon2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'SDO',
        supervisorName: 'Prof. V.K. Gunjal',
      ),
      Assignment(
        id: 'ASN-048',
        studentId: 'STU-048',
        locationId: 'LOC-10',
        supervisorId: 'SV-05',
        workDescription: 'NSS activity record maintenance and dispatch filing',
        shiftWindows: const [shiftAfternoon2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'SDO',
        supervisorName: 'Prof. V.K. Gunjal',
      ),
      Assignment(
        id: 'ASN-049',
        studentId: 'STU-049',
        locationId: 'LOC-10',
        supervisorId: 'SV-05',
        workDescription: 'Student grievance desk log and circular distribution',
        shiftWindows: const [shiftAfternoon2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'SDO',
        supervisorName: 'Prof. V.K. Gunjal',
      ),

      // 11. Gymkhana (LOC-11 • SV-03)
      Assignment(
        id: 'ASN-050',
        studentId: 'STU-050',
        locationId: 'LOC-11',
        supervisorId: 'SV-03',
        workDescription: 'Gymnasium weight stack inspection and user register',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Gymkhana',
        supervisorName: 'Dr. Anjali Patil',
      ),
      Assignment(
        id: 'ASN-051',
        studentId: 'STU-051',
        locationId: 'LOC-11',
        supervisorId: 'SV-03',
        workDescription: 'Sports gear issue & return verification',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Gymkhana',
        supervisorName: 'Dr. Anjali Patil',
      ),
      Assignment(
        id: 'ASN-052',
        studentId: 'STU-052',
        locationId: 'LOC-11',
        supervisorId: 'SV-03',
        workDescription: 'Badminton court booking schedule management',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Gymkhana',
        supervisorName: 'Dr. Anjali Patil',
      ),
      Assignment(
        id: 'ASN-053',
        studentId: 'STU-053',
        locationId: 'LOC-11',
        supervisorId: 'SV-03',
        workDescription: 'Table tennis arena maintenance & score board log',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Gymkhana',
        supervisorName: 'Dr. Anjali Patil',
      ),

      // 12. Dispensary (LOC-12 • SV-08)
      Assignment(
        id: 'ASN-054',
        studentId: 'STU-054',
        locationId: 'LOC-12',
        supervisorId: 'SV-08',
        workDescription: 'Daily patient visitor registration & token issuance',
        shiftWindows: const [shiftAfternoon2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Dispensary',
        supervisorName: 'Dr. S.M. Hase',
      ),
      Assignment(
        id: 'ASN-055',
        studentId: 'STU-055',
        locationId: 'LOC-12',
        supervisorId: 'SV-08',
        workDescription: 'Medicine expiry register sorting and first-aid replenishment',
        shiftWindows: const [shiftAfternoon2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Dispensary',
        supervisorName: 'Dr. S.M. Hase',
      ),
      Assignment(
        id: 'ASN-056',
        studentId: 'STU-056',
        locationId: 'LOC-12',
        supervisorId: 'SV-08',
        workDescription: 'Emergency vehicle log and clinic hygiene check',
        shiftWindows: const [shiftAfternoon2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Dispensary',
        supervisorName: 'Dr. S.M. Hase',
      ),

      // 13. Incubation Centre (LOC-13 • SV-06)
      Assignment(
        id: 'ASN-057',
        studentId: 'STU-057',
        locationId: 'LOC-13',
        supervisorId: 'SV-06',
        workDescription: 'Startup cubicle meeting room booking & IT assistance',
        shiftWindows: const [shiftAfternoon2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Incubation',
        supervisorName: 'Dr. P.R. Gorde',
      ),
      Assignment(
        id: 'ASN-058',
        studentId: 'STU-058',
        locationId: 'LOC-13',
        supervisorId: 'SV-06',
        workDescription: 'Innovation showcase visitor register & presentation setup',
        shiftWindows: const [shiftAfternoon2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Incubation',
        supervisorName: 'Dr. P.R. Gorde',
      ),
      Assignment(
        id: 'ASN-059',
        studentId: 'STU-059',
        locationId: 'LOC-13',
        supervisorId: 'SV-06',
        workDescription: 'Makerspace 3D printer queue and component catalog',
        shiftWindows: const [shiftAfternoon2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Incubation',
        supervisorName: 'Dr. P.R. Gorde',
      ),
      Assignment(
        id: 'ASN-060',
        studentId: 'STU-060',
        locationId: 'LOC-13',
        supervisorId: 'SV-06',
        workDescription: 'Patenting desk file documentation and workshop registration',
        shiftWindows: const [shiftAfternoon2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Incubation',
        supervisorName: 'Dr. P.R. Gorde',
      ),

      // 14. Guest House (LOC-14 • SV-10)
      Assignment(
        id: 'ASN-061',
        studentId: 'STU-061',
        locationId: 'LOC-14',
        supervisorId: 'SV-10',
        workDescription: 'VIP reception desk guest arrival entry',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Guest House',
        supervisorName: 'Mr. D.M. Dighe',
      ),
      Assignment(
        id: 'ASN-062',
        studentId: 'STU-062',
        locationId: 'LOC-14',
        supervisorId: 'SV-10',
        workDescription: 'Room key inventory and dining register maintenance',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Guest House',
        supervisorName: 'Mr. D.M. Dighe',
      ),
      Assignment(
        id: 'ASN-063',
        studentId: 'STU-063',
        locationId: 'LOC-14',
        supervisorId: 'SV-10',
        workDescription: 'Lounge and conference room meeting logistics',
        shiftWindows: const [shiftMorning1h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Guest House',
        supervisorName: 'Mr. D.M. Dighe',
      ),
      Assignment(
        id: 'ASN-064',
        studentId: 'STU-064',
        locationId: 'LOC-14',
        supervisorId: 'SV-10',
        workDescription: 'Guest feedback form cataloging and amenities audit',
        shiftWindows: const [shiftEvening2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'Guest House',
        supervisorName: 'Mr. D.M. Dighe',
      ),

      // 15. TPO Office (LOC-15 • SV-09)
      Assignment(
        id: 'ASN-065',
        studentId: 'STU-065',
        locationId: 'LOC-15',
        supervisorId: 'SV-09',
        workDescription: 'Placement drive company registration desk support',
        shiftWindows: const [shiftAfternoon2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'TPO Office',
        supervisorName: 'Prof. R.S. Tambe',
      ),
      Assignment(
        id: 'ASN-066',
        studentId: 'STU-066',
        locationId: 'LOC-15',
        supervisorId: 'SV-09',
        workDescription: 'Student interview schedule calling and attendance register',
        shiftWindows: const [shiftAfternoon2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'TPO Office',
        supervisorName: 'Prof. R.S. Tambe',
      ),
      Assignment(
        id: 'ASN-067',
        studentId: 'STU-067',
        locationId: 'LOC-15',
        supervisorId: 'SV-09',
        workDescription: 'Auditorium pre-placement talk audio-visual setup',
        shiftWindows: const [shiftAfternoon2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'TPO Office',
        supervisorName: 'Prof. R.S. Tambe',
      ),
      Assignment(
        id: 'ASN-068',
        studentId: 'STU-068',
        locationId: 'LOC-15',
        supervisorId: 'SV-09',
        workDescription: 'Offer letter archive filing and verification records',
        shiftWindows: const [shiftAfternoon2h],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: 'TPO Office',
        supervisorName: 'Prof. R.S. Tambe',
      ),
    ];
  }
}
