import '../../core/models/models.dart';

/// Authentic institutional seed data for Amrutvahini College of Engineering (AVCOE),
/// K.B.P. Earn & Learn Scheme 2026-27. Generated from the official
/// "Updated KBP Time and Work Allotment 2026-27" allotment sheet.
///
/// Fidelity rules (no fabrication):
///  * 15 official work locations, 10 named supervisors-in-charge, 68 student allotments.
///  * Real student names, time slots and work descriptions from the sheet.
///  * The sheet gives NO college roll numbers; `rollNumber` carries a unique
///    Earn & Learn enrolment ID (EL2627-###) so uniqueness holds. Display it as
///    "Earn & Learn ID", or import real roll numbers later.
///  * contact / department / class exist only for office-location students; hostel
///    and library students are left null and surface as "Not available"/"Not specified".
///  * No geofence coordinates are set, so location check-in honestly shows
///    "Configuration required" until real coordinates are provided.
///  * Civil Lab, Dispensary and Incubation have no named supervisor in the sheet;
///    their assignments carry supervisorName "Not assigned".
class AvcoeSeedData {
  AvcoeSeedData._();

  // ---------------------------------------------------------------------------
  // 15 Official Institutional Work Locations
  // ---------------------------------------------------------------------------
  static const List<Location> locations = [
    Location(
      id: "LOC-01",
      name: "Kalsubai Hostel (Old)",
      description: "Hostel attendance, discipline, leave-form checking and register entry",
      supervisorIds: ["SV-02", "SV-03"],
      status: LocationStatus.active,
    ),
    Location(
      id: "LOC-02",
      name: "Krushnavanti Hostel (New)",
      description: "New hostel floor-wise attendance, discipline, cleanliness and register entry",
      supervisorIds: ["SV-02", "SV-03"],
      status: LocationStatus.active,
    ),
    Location(
      id: "LOC-03",
      name: "Study Hall",
      description:
          "Study hall / CCF maintenance and internet-usage record keeping",
      supervisorIds: ["SV-03"],
      status: LocationStatus.active,
    ),
    Location(
      id: "LOC-04",
      name: "Play Ground and Gardening",
      description: "Sports material records, ground upkeep and yoga activity",
      supervisorIds: ["SV-04"],
      status: LocationStatus.active,
    ),
    Location(
      id: "LOC-05",
      name: "Harishchandragadh Hostel",
      description: "Hostel attendance, discipline, leave-form checking and register entry",
      supervisorIds: ["SV-02"],
      status: LocationStatus.active,
    ),
    Location(
      id: "LOC-06",
      name: "Sinhagad Hostel",
      description: "Hostel floor-wise attendance, discipline and office work",
      supervisorIds: ["SV-02", "SV-05"],
      status: LocationStatus.active,
    ),
    Location(
      id: "LOC-07",
      name: "Sajjangad Hostel",
      description: "Hostel attendance, discipline and register maintenance",
      supervisorIds: ["SV-02"],
      status: LocationStatus.active,
    ),
    Location(
      id: "LOC-08",
      name: "Library",
      description:
          "Library discipline, study-room records and night-library assistance",
      supervisorIds: ["SV-01"],
      status: LocationStatus.active,
    ),
    Location(
      id: "LOC-09",
      name: "Civil Lab",
      description: "Civil materials-testing lab assistance",
      supervisorIds: [],
      status: LocationStatus.attention,
    ),
    Location(
      id: "LOC-10",
      name: "SDO",
      description: "Student Development Office record keeping and support",
      supervisorIds: ["SV-08"],
      status: LocationStatus.active,
    ),
    Location(
      id: "LOC-11",
      name: "Gymkhana",
      description: "Gymkhana sports equipment and fitness arena support",
      supervisorIds: ["SV-06"],
      status: LocationStatus.active,
    ),
    Location(
      id: "LOC-12",
      name: "Dispensary",
      description: "Dispensary / first-aid centre assistance and visitor log",
      supervisorIds: [],
      status: LocationStatus.attention,
    ),
    Location(
      id: "LOC-13",
      name: "Incubation",
      description: "Incubation & innovation cell desk assistance",
      supervisorIds: [],
      status: LocationStatus.attention,
    ),
    Location(
      id: "LOC-14",
      name: "Guest House",
      description: "Guest house reception and hospitality support",
      supervisorIds: ["SV-07"],
      status: LocationStatus.active,
    ),
    Location(
      id: "LOC-15",
      name: "TPO Office",
      description: "Training & Placement drive coordination and records",
      supervisorIds: ["SV-09", "SV-10"],
      status: LocationStatus.active,
    ),
  ];

  // ---------------------------------------------------------------------------
  // 10 Named Institutional Supervisors (as listed in the allotment sheet)
  // ---------------------------------------------------------------------------
  static const List<Supervisor> supervisors = [
    Supervisor(
      id: "SV-01",
      name: "Mr. K.J. Dhage",
      department: "Library",
      assignedLocationIds: ["LOC-08"],
      status: SupervisorStatus.onDuty,
    ),
    Supervisor(
      id: "SV-02",
      name: "Prof. V.S. Ubale",
      department: "Hostel Administration",
      assignedLocationIds: [
        "LOC-01",
        "LOC-02",
        "LOC-05",
        "LOC-06",
        "LOC-07",
      ],
      status: SupervisorStatus.onDuty,
    ),
    Supervisor(
      id: "SV-03",
      name: "Miss. Savita Punekar",
      department: "Hostel & Study Hall",
      assignedLocationIds: ["LOC-01", "LOC-02", "LOC-03"],
      status: SupervisorStatus.onDuty,
    ),
    Supervisor(
      id: "SV-04",
      name: "Miss. A.N. Nawale",
      department: "Sports & Gardening",
      assignedLocationIds: ["LOC-04"],
      status: SupervisorStatus.onDuty,
    ),
    Supervisor(
      id: "SV-05",
      name: "Dr. P.N. Nagare",
      department: "Hostel Administration",
      assignedLocationIds: ["LOC-06"],
      status: SupervisorStatus.onDuty,
    ),
    Supervisor(
      id: "SV-06",
      name: "Mr. B.S. Shinde",
      department: "Gymkhana",
      assignedLocationIds: ["LOC-11"],
      status: SupervisorStatus.onDuty,
    ),
    Supervisor(
      id: "SV-07",
      name: "Mr. Khule",
      department: "Guest House Administration",
      assignedLocationIds: ["LOC-14"],
      status: SupervisorStatus.onDuty,
    ),
    Supervisor(
      id: "SV-08",
      name: "Prof. R.S. Pawase",
      department: "Student Development Office",
      assignedLocationIds: ["LOC-10"],
      status: SupervisorStatus.onDuty,
    ),
    Supervisor(
      id: "SV-09",
      name: "Prof. Pravin Wakchaure",
      department: "Training & Placement Cell",
      assignedLocationIds: ["LOC-15"],
      status: SupervisorStatus.onDuty,
    ),
    Supervisor(
      id: "SV-10",
      name: "Prof. S.C. Deshmukh",
      department: "Training & Placement Cell",
      assignedLocationIds: ["LOC-15"],
      status: SupervisorStatus.onDuty,
    ),
  ];

  // ---------------------------------------------------------------------------
  // 68 Authentic Student Records (real names from the allotment sheet)
  // ---------------------------------------------------------------------------
  static const List<Student> students = [
    Student(
      id: "STU-001",
      name: "DHANWATE RUTUJA NITIN",
      rollNumber: "EL2627-001",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-002",
      name: "Karale Gayatri Kishor",
      rollNumber: "EL2627-002",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-003",
      name: "CHASKAR TRUPTI BALU",
      rollNumber: "EL2627-003",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-004",
      name: "Gadhave Samiksha Sandip",
      rollNumber: "EL2627-004",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-005",
      name: "Lolage Anushka Ganesh",
      rollNumber: "EL2627-005",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-006",
      name: "Shinde Akanksha kondiram",
      rollNumber: "EL2627-006",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-007",
      name: "MHASE DNYANESHWARI SANTOSH",
      rollNumber: "EL2627-007",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-008",
      name: "Pathade Sakshi Gorakshanath",
      rollNumber: "EL2627-008",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-009",
      name: "JADHAV SWARUPA VITTHAL",
      rollNumber: "EL2627-009",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-010",
      name: "Pise Gayatri Adinath",
      rollNumber: "EL2627-010",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-011",
      name: "Dhere Divya Bajirao",
      rollNumber: "EL2627-011",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-012",
      name: "Take Dnyaneshwari Anil",
      rollNumber: "EL2627-012",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-013",
      name: "Shinde Kalyani Bharat",
      rollNumber: "EL2627-013",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-014",
      name: "MHASE GAURI NANASAHEB",
      rollNumber: "EL2627-014",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-015",
      name: "Purane Vaishnavi Laxman",
      rollNumber: "EL2627-015",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-016",
      name: "Waghaskar Sanskruti Balasaheb",
      rollNumber: "EL2627-016",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-017",
      name: "SHARMA PURVA VIKAS",
      rollNumber: "EL2627-017",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-018",
      name: "Wavhal Apeksha Dattatray",
      rollNumber: "EL2627-018",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-019",
      name: "Asane komal Sanjay",
      rollNumber: "EL2627-019",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-020",
      name: "Naik Sneha Avinash",
      rollNumber: "EL2627-020",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-021",
      name: "Hande Samruddhi Ganesh",
      rollNumber: "EL2627-021",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-022",
      name: "Gaikwad Shraddha Navnath",
      rollNumber: "EL2627-022",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-023",
      name: "Vaishnavi Bhaurao Dushing",
      rollNumber: "EL2627-023",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-024",
      name: "Anap Bhagyashree Nanasaheb",
      rollNumber: "EL2627-024",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-025",
      name: "Kadu Ankita Prabhakar",
      rollNumber: "EL2627-025",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-026",
      name: "Deokar Vidhi Rudraji",
      rollNumber: "EL2627-026",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-027",
      name: "Gaikwad Akanksha Tanhaji",
      rollNumber: "EL2627-027",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-028",
      name: "Thorat Mayuri Vilas",
      rollNumber: "EL2627-028",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-029",
      name: "Nikam kalyani Bhaiyasaheb",
      rollNumber: "EL2627-029",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-030",
      name: "Lande Priyanka Shivaji",
      rollNumber: "EL2627-030",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-031",
      name: "Gangurde Vishakha Gorakh",
      rollNumber: "EL2627-031",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-032",
      name: "Watpade Sayali Navanath",
      rollNumber: "EL2627-032",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-033",
      name: "Kamble Shravani Rajendra",
      rollNumber: "EL2627-033",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-034",
      name: "Dhumal Tanvi Santosh",
      rollNumber: "EL2627-034",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-035",
      name: "Gadekar Om Sachin",
      rollNumber: "EL2627-035",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-036",
      name: "TAPARE DARSHAN BABASAHEB",
      rollNumber: "EL2627-036",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-037",
      name: "Chaitanya Annasaheb Matsagar",
      rollNumber: "EL2627-037",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-038",
      name: "ANDHARE PRANAV ARUN",
      rollNumber: "EL2627-038",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-039",
      name: "Bokhare Ashutosh Suryaprakash",
      rollNumber: "EL2627-039",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-040",
      name: "Phatangare Kartik Vilas",
      rollNumber: "EL2627-040",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-041",
      name: "CHAUDHARI NISHANT PRASHANT",
      rollNumber: "EL2627-041",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-042",
      name: "Bhalerao Ritesh Ramrao",
      rollNumber: "EL2627-042",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-043",
      name: "Kerkal Ganesh Sitaram",
      rollNumber: "EL2627-043",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-044",
      name: "Ghawat Shivprasad Appasaheb",
      rollNumber: "EL2627-044",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-045",
      name: "Gawade Yash Santosh",
      rollNumber: "EL2627-045",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-046",
      name: "Sayyad Arshad Raju",
      rollNumber: "EL2627-046",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-047",
      name: "Ghortale Suraj sopan",
      rollNumber: "EL2627-047",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-048",
      name: "Waghule Pranav Sanjay",
      rollNumber: "EL2627-048",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-049",
      name: "MAGARE TEJAS MURLIDHAR",
      rollNumber: "EL2627-049",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-050",
      name: "Chaudhari vaibhav Laxman",
      rollNumber: "EL2627-050",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-051",
      name: "Magare Yash Satish",
      rollNumber: "EL2627-051",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-052",
      name: "Rohan Rajendra Raundal",
      rollNumber: "EL2627-052",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-053",
      name: "Shinde Ritesh Kedarnath",
      rollNumber: "EL2627-053",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-054",
      name: "NALAGE TEJAS SITARAM",
      rollNumber: "EL2627-054",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-055",
      name: "Deshmukh Prasad Badamrao",
      rollNumber: "EL2627-055",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-056",
      name: "Harshal Namdeo Pabale",
      rollNumber: "EL2627-056",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-057",
      name: "Nighute Ajinkya Vilas",
      rollNumber: "EL2627-057",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-058",
      name: "Kharde Saurabh Ganesh",
      rollNumber: "EL2627-058",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-059",
      name: "Kunal Dilip Pawar",
      rollNumber: "EL2627-059",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-060",
      name: "Varne Mukund Ravindra",
      rollNumber: "EL2627-060",
      department: null,
      className: null,
      contact: null,
    ),
    Student(
      id: "STU-061",
      name: "Abhijeet Dilip Gholap",
      rollNumber: "EL2627-061",
      department: "E&TC",
      className: "BE",
      contact: "+91 9822449027",
    ),
    Student(
      id: "STU-062",
      name: "SONSALE DHANANJAY GORAKH",
      rollNumber: "EL2627-062",
      department: "Civil",
      className: "TE",
      contact: "+91 9028067481",
    ),
    Student(
      id: "STU-063",
      name: "EDKE HARSHAL DIGAMBAR",
      rollNumber: "EL2627-063",
      department: "IT",
      className: "TE",
      contact: "+91 8208953692",
    ),
    Student(
      id: "STU-064",
      name: "Wagh Avinash Suresh",
      rollNumber: "EL2627-064",
      department: "E&CE",
      className: "BE",
      contact: "+91 8767642526",
    ),
    Student(
      id: "STU-065",
      name: "Wakchaure Rahul Navanath",
      rollNumber: "EL2627-065",
      department: "ME",
      className: "BE",
      contact: "+91 9403778472",
    ),
    Student(
      id: "STU-066",
      name: "Narendra Sanjay Koli",
      rollNumber: "EL2627-066",
      department: "ME",
      className: "BE",
      contact: "+91 9284765922",
    ),
    Student(
      id: "STU-067",
      name: "Chaudhari Atharv Dattatray",
      rollNumber: "EL2627-067",
      department: "E&CE",
      className: "BE",
      contact: "+91 8010456041",
    ),
    Student(
      id: "STU-068",
      name: "Shinde Kirshna Sanjay",
      rollNumber: "EL2627-068",
      department: "A&R",
      className: "BE",
      contact: "+91 7773964752",
    ),
  ];

  // ---------------------------------------------------------------------------
  // 68 Student Assignments (real time slots + duties from the allotment sheet)
  // ---------------------------------------------------------------------------
  static List<Assignment> createAssignments() {
    final now = DateTime.now();
    final startOfMonth = DateTime(now.year, now.month, 1);

    return [
      Assignment(
        id: "ASN-001",
        studentId: "STU-001",
        locationId: "LOC-01",
        supervisorId: "SV-02",
        workDescription: "Attendance & Discipline",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 21, minutes: 0),
            end: Duration(hours: 24, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Kalsubai Hostel (Old)",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-002",
        studentId: "STU-002",
        locationId: "LOC-01",
        supervisorId: "SV-02",
        workDescription: "Attendance & Discipline",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 20, minutes: 0),
            end: Duration(hours: 23, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Kalsubai Hostel (Old)",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-003",
        studentId: "STU-003",
        locationId: "LOC-01",
        supervisorId: "SV-02",
        workDescription: "Attendance & Discipline",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 20, minutes: 0),
            end: Duration(hours: 23, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Kalsubai Hostel (Old)",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-004",
        studentId: "STU-004",
        locationId: "LOC-01",
        supervisorId: "SV-02",
        workDescription: "Leave Form Checking",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 21, minutes: 0),
            end: Duration(hours: 24, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Kalsubai Hostel (Old)",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-005",
        studentId: "STU-005",
        locationId: "LOC-01",
        supervisorId: "SV-02",
        workDescription: "Leave Form Checking",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 20, minutes: 0),
            end: Duration(hours: 23, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Kalsubai Hostel (Old)",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-006",
        studentId: "STU-006",
        locationId: "LOC-01",
        supervisorId: "SV-02",
        workDescription: "Maintain Register Entry",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 20, minutes: 0),
            end: Duration(hours: 23, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Kalsubai Hostel (Old)",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-007",
        studentId: "STU-007",
        locationId: "LOC-01",
        supervisorId: "SV-02",
        workDescription: "Office Work Maintain Register Entry",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 17, minutes: 0),
            end: Duration(hours: 20, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Kalsubai Hostel (Old)",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-008",
        studentId: "STU-008",
        locationId: "LOC-01",
        supervisorId: "SV-02",
        workDescription: "Office Work &Maintain Register Entry",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 18, minutes: 0),
            end: Duration(hours: 21, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Kalsubai Hostel (Old)",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-009",
        studentId: "STU-009",
        locationId: "LOC-02",
        supervisorId: "SV-02",
        workDescription: "Attendance & Discipline Ground Floor",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 21, minutes: 0),
            end: Duration(hours: 24, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Krushnavanti Hostel (New)",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-010",
        studentId: "STU-010",
        locationId: "LOC-02",
        supervisorId: "SV-02",
        workDescription: "Attendance & Discipline at 1st Floor",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 21, minutes: 0),
            end: Duration(hours: 24, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Krushnavanti Hostel (New)",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-011",
        studentId: "STU-011",
        locationId: "LOC-02",
        supervisorId: "SV-02",
        workDescription: "Attendance & Discipline at 3rd Floor",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 20, minutes: 0),
            end: Duration(hours: 23, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Krushnavanti Hostel (New)",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-012",
        studentId: "STU-012",
        locationId: "LOC-02",
        supervisorId: "SV-02",
        workDescription: "Cleanliness & Discipline at Gound, 1st Floor",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 20, minutes: 0),
            end: Duration(hours: 23, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Krushnavanti Hostel (New)",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-013",
        studentId: "STU-013",
        locationId: "LOC-02",
        supervisorId: "SV-02",
        workDescription: "Cleanliness & Discipline at 2nd & 3rd Floor",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 20, minutes: 0),
            end: Duration(hours: 22, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Krushnavanti Hostel (New)",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-014",
        studentId: "STU-014",
        locationId: "LOC-02",
        supervisorId: "SV-02",
        workDescription: "Maintain Register Entry",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 18, minutes: 0),
            end: Duration(hours: 21, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Krushnavanti Hostel (New)",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-015",
        studentId: "STU-015",
        locationId: "LOC-02",
        supervisorId: "SV-02",
        workDescription: "Leave Form Checking",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 20, minutes: 0),
            end: Duration(hours: 22, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Krushnavanti Hostel (New)",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-016",
        studentId: "STU-016",
        locationId: "LOC-02",
        supervisorId: "SV-02",
        workDescription: "Maintain Register Entry",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 17, minutes: 0),
            end: Duration(hours: 20, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Krushnavanti Hostel (New)",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-017",
        studentId: "STU-017",
        locationId: "LOC-02",
        supervisorId: "SV-02",
        workDescription: "Office Work",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 18, minutes: 0),
            end: Duration(hours: 21, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Krushnavanti Hostel (New)",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-018",
        studentId: "STU-018",
        locationId: "LOC-03",
        supervisorId: "SV-03",
        workDescription: "CCF Maintenance & Cleanliness and Movie Club Keep record of students using internet.",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 18, minutes: 0),
            end: Duration(hours: 21, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Study Hall",
        supervisorName: "Miss. Savita Punekar",
      ),
      Assignment(
        id: "ASN-019",
        studentId: "STU-019",
        locationId: "LOC-03",
        supervisorId: "SV-03",
        workDescription: "CCF Maintenance & Cleanliness and Movie Club Keep record of students using internet.",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 19, minutes: 0),
            end: Duration(hours: 22, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Study Hall",
        supervisorName: "Miss. Savita Punekar",
      ),
      Assignment(
        id: "ASN-020",
        studentId: "STU-020",
        locationId: "LOC-03",
        supervisorId: "SV-03",
        workDescription: "CCF Maintenance & Cleanliness and Movie Club Keep record of students using internet.",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 20, minutes: 0),
            end: Duration(hours: 23, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Study Hall",
        supervisorName: "Miss. Savita Punekar",
      ),
      Assignment(
        id: "ASN-021",
        studentId: "STU-021",
        locationId: "LOC-04",
        supervisorId: "SV-04",
        workDescription:
            "- Maintain Records of sports material issued - Yoga Activity",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 16, minutes: 30),
            end: Duration(hours: 19, minutes: 30),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Play Ground and Gardening",
        supervisorName: "Miss. A.N. Nawale",
      ),
      Assignment(
        id: "ASN-022",
        studentId: "STU-022",
        locationId: "LOC-04",
        supervisorId: "SV-04",
        workDescription:
            "- Maintain Records of sports material issued - Yoga Activity",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 17, minutes: 0),
            end: Duration(hours: 20, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Play Ground and Gardening",
        supervisorName: "Miss. A.N. Nawale",
      ),
      Assignment(
        id: "ASN-023",
        studentId: "STU-023",
        locationId: "LOC-04",
        supervisorId: "SV-04",
        workDescription:
            "- Maintain Records of sports material issued - Yoga Activity",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 16, minutes: 0),
            end: Duration(hours: 19, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Play Ground and Gardening",
        supervisorName: "Miss. A.N. Nawale",
      ),
      Assignment(
        id: "ASN-024",
        studentId: "STU-024",
        locationId: "LOC-05",
        supervisorId: "SV-02",
        workDescription: "Leave Form Checking",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 19, minutes: 0),
            end: Duration(hours: 22, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Harishchandragadh Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-025",
        studentId: "STU-025",
        locationId: "LOC-05",
        supervisorId: "SV-02",
        workDescription: "Maintain Register Entry",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 18, minutes: 0),
            end: Duration(hours: 21, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Harishchandragadh Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-026",
        studentId: "STU-026",
        locationId: "LOC-05",
        supervisorId: "SV-02",
        workDescription: "Attendance & Discipline",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 21, minutes: 0),
            end: Duration(hours: 24, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Harishchandragadh Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-027",
        studentId: "STU-027",
        locationId: "LOC-05",
        supervisorId: "SV-02",
        workDescription: "Leave Form Checking",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 20, minutes: 0),
            end: Duration(hours: 23, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Harishchandragadh Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-028",
        studentId: "STU-028",
        locationId: "LOC-05",
        supervisorId: "SV-02",
        workDescription: "Attendance & Discipline",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 21, minutes: 0),
            end: Duration(hours: 24, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Harishchandragadh Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-029",
        studentId: "STU-029",
        locationId: "LOC-05",
        supervisorId: "SV-02",
        workDescription: "Maintain Register Entry",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 18, minutes: 0),
            end: Duration(hours: 21, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Harishchandragadh Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-030",
        studentId: "STU-030",
        locationId: "LOC-05",
        supervisorId: "SV-02",
        workDescription: "Attendance & Discipline",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 21, minutes: 0),
            end: Duration(hours: 24, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Harishchandragadh Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-031",
        studentId: "STU-031",
        locationId: "LOC-05",
        supervisorId: "SV-02",
        workDescription: "Attendance & Discipline",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 18, minutes: 0),
            end: Duration(hours: 21, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Harishchandragadh Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-032",
        studentId: "STU-032",
        locationId: "LOC-05",
        supervisorId: "SV-02",
        workDescription: "Office Work & Leave Form Checking",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 17, minutes: 0),
            end: Duration(hours: 20, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Harishchandragadh Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-033",
        studentId: "STU-033",
        locationId: "LOC-05",
        supervisorId: "SV-02",
        workDescription: "Attendance & Discipline",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 21, minutes: 0),
            end: Duration(hours: 24, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Harishchandragadh Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-034",
        studentId: "STU-034",
        locationId: "LOC-05",
        supervisorId: "SV-02",
        workDescription: "Office Work & Leave Form Checking",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 20, minutes: 0),
            end: Duration(hours: 23, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Harishchandragadh Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-035",
        studentId: "STU-035",
        locationId: "LOC-06",
        supervisorId: "SV-02",
        workDescription: "Attendance & Discipline at Ground Floor",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 21, minutes: 0),
            end: Duration(hours: 24, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Sinhagad Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-036",
        studentId: "STU-036",
        locationId: "LOC-06",
        supervisorId: "SV-02",
        workDescription: "Attendance & Discipline at 1st & 2nd Floor",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 20, minutes: 0),
            end: Duration(hours: 23, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Sinhagad Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-037",
        studentId: "STU-037",
        locationId: "LOC-06",
        supervisorId: "SV-02",
        workDescription: "Office Work",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 18, minutes: 0),
            end: Duration(hours: 21, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Sinhagad Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-038",
        studentId: "STU-038",
        locationId: "LOC-06",
        supervisorId: "SV-02",
        workDescription: "Office Work",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 19, minutes: 0),
            end: Duration(hours: 22, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Sinhagad Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-039",
        studentId: "STU-039",
        locationId: "LOC-06",
        supervisorId: "SV-02",
        workDescription: "Maintain Register Entry",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 19, minutes: 0),
            end: Duration(hours: 22, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Sinhagad Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-040",
        studentId: "STU-040",
        locationId: "LOC-06",
        supervisorId: "SV-02",
        workDescription: "Attendance of engg. Students 1st floor",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 21, minutes: 0),
            end: Duration(hours: 24, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Sinhagad Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-041",
        studentId: "STU-041",
        locationId: "LOC-06",
        supervisorId: "SV-02",
        workDescription: "Attendance of engg. Students 2nd floor",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 20, minutes: 0),
            end: Duration(hours: 23, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Sinhagad Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-042",
        studentId: "STU-042",
        locationId: "LOC-06",
        supervisorId: "SV-02",
        workDescription: "Descipline and hostel checking",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 21, minutes: 0),
            end: Duration(hours: 23, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Sinhagad Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-043",
        studentId: "STU-043",
        locationId: "LOC-06",
        supervisorId: "SV-02",
        workDescription: "Leave Form Checking",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 18, minutes: 0),
            end: Duration(hours: 21, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Sinhagad Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-044",
        studentId: "STU-044",
        locationId: "LOC-06",
        supervisorId: "SV-02",
        workDescription: "Leave Form Checking",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 19, minutes: 0),
            end: Duration(hours: 22, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Sinhagad Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-045",
        studentId: "STU-045",
        locationId: "LOC-07",
        supervisorId: "SV-02",
        workDescription: "Attendance & Discipline at Ground Floor",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 21, minutes: 0),
            end: Duration(hours: 24, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Sajjangad Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-046",
        studentId: "STU-046",
        locationId: "LOC-07",
        supervisorId: "SV-02",
        workDescription: "Attendance & Discipline at 1st & 2nd Floor",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 20, minutes: 0),
            end: Duration(hours: 23, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Sajjangad Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-047",
        studentId: "STU-047",
        locationId: "LOC-07",
        supervisorId: "SV-02",
        workDescription: "Biometrica Entry checkup",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 20, minutes: 0),
            end: Duration(hours: 23, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Sajjangad Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-048",
        studentId: "STU-048",
        locationId: "LOC-07",
        supervisorId: "SV-02",
        workDescription: "Maintain Register Entry",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 19, minutes: 0),
            end: Duration(hours: 22, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Sajjangad Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-049",
        studentId: "STU-049",
        locationId: "LOC-07",
        supervisorId: "SV-02",
        workDescription: "Attendence of EL students & Leave Form Checking",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 21, minutes: 0),
            end: Duration(hours: 24, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Sajjangad Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-050",
        studentId: "STU-050",
        locationId: "LOC-07",
        supervisorId: "SV-02",
        workDescription: "Maintain Register Entry",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 18, minutes: 0),
            end: Duration(hours: 21, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Sajjangad Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-051",
        studentId: "STU-051",
        locationId: "LOC-07",
        supervisorId: "SV-02",
        workDescription: "Descipline and hostel checking",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 20, minutes: 0),
            end: Duration(hours: 23, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Sajjangad Hostel",
        supervisorName: "Prof. V.S. Ubale",
      ),
      Assignment(
        id: "ASN-052",
        studentId: "STU-052",
        locationId: "LOC-08",
        supervisorId: "SV-01",
        workDescription: "Maintain discipline and silence in the library. Work for night library as per direction. Keep records of students visiting to study room. Report immediately regarding any misbehavior of any student. Maintain discipline and silence in the Dronagiri library. Keep records of students visiting to study room. Report immediately regarding any misbehavior of any student.",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 17, minutes: 0),
            end: Duration(hours: 20, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Library",
        supervisorName: "Mr. K.J. Dhage",
      ),
      Assignment(
        id: "ASN-053",
        studentId: "STU-053",
        locationId: "LOC-08",
        supervisorId: "SV-01",
        workDescription: "Maintain discipline and silence in the library. Work for night library as per direction. Keep records of students visiting to study room. Report immediately regarding any misbehavior of any student. Maintain discipline and silence in the Dronagiri library. Keep records of students visiting to study room. Report immediately regarding any misbehavior of any student.",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 18, minutes: 0),
            end: Duration(hours: 21, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Library",
        supervisorName: "Mr. K.J. Dhage",
      ),
      Assignment(
        id: "ASN-054",
        studentId: "STU-054",
        locationId: "LOC-08",
        supervisorId: "SV-01",
        workDescription: "Maintain discipline and silence in the library. Work for night library as per direction. Keep records of students visiting to study room. Report immediately regarding any misbehavior of any student. Maintain discipline and silence in the Dronagiri library. Keep records of students visiting to study room. Report immediately regarding any misbehavior of any student.",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 20, minutes: 0),
            end: Duration(hours: 23, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Library",
        supervisorName: "Mr. K.J. Dhage",
      ),
      Assignment(
        id: "ASN-055",
        studentId: "STU-055",
        locationId: "LOC-08",
        supervisorId: "SV-01",
        workDescription: "Maintain discipline and silence in the library. Work for night library as per direction. Keep records of students visiting to study room. Report immediately regarding any misbehavior of any student. Maintain discipline and silence in the Dronagiri library. Keep records of students visiting to study room. Report immediately regarding any misbehavior of any student.",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 21, minutes: 0),
            end: Duration(hours: 24, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Library",
        supervisorName: "Mr. K.J. Dhage",
      ),
      Assignment(
        id: "ASN-056",
        studentId: "STU-056",
        locationId: "LOC-08",
        supervisorId: "SV-01",
        workDescription: "Maintain discipline and silence in the library. Work for night library as per direction. Keep records of students visiting to study room. Report immediately regarding any misbehavior of any student. Maintain discipline and silence in the Dronagiri library. Keep records of students visiting to study room. Report immediately regarding any misbehavior of any student.",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 13, minutes: 0),
            end: Duration(hours: 14, minutes: 0),
          ),
          ShiftWindow(
            start: Duration(hours: 16, minutes: 0),
            end: Duration(hours: 17, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Library",
        supervisorName: "Mr. K.J. Dhage",
      ),
      Assignment(
        id: "ASN-057",
        studentId: "STU-057",
        locationId: "LOC-08",
        supervisorId: "SV-01",
        workDescription: "Maintain discipline and silence in the library. Work for night library as per direction. Keep records of students visiting to study room. Report immediately regarding any misbehavior of any student. Maintain discipline and silence in the Dronagiri library. Keep records of students visiting to study room. Report immediately regarding any misbehavior of any student.",
        shiftWindows: const [],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Library",
        supervisorName: "Mr. K.J. Dhage",
      ),
      Assignment(
        id: "ASN-058",
        studentId: "STU-058",
        locationId: "LOC-08",
        supervisorId: "SV-01",
        workDescription: "Maintain discipline and silence in the library. Work for night library as per direction. Keep records of students visiting to study room. Report immediately regarding any misbehavior of any student. Maintain discipline and silence in the Dronagiri library. Keep records of students visiting to study room. Report immediately regarding any misbehavior of any student.",
        shiftWindows: const [],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Library",
        supervisorName: "Mr. K.J. Dhage",
      ),
      Assignment(
        id: "ASN-059",
        studentId: "STU-059",
        locationId: "LOC-08",
        supervisorId: "SV-01",
        workDescription: "Maintain discipline and silence in the library. Work for night library as per direction. Keep records of students visiting to study room. Report immediately regarding any misbehavior of any student. Maintain discipline and silence in the Dronagiri library. Keep records of students visiting to study room. Report immediately regarding any misbehavior of any student.",
        shiftWindows: const [],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Library",
        supervisorName: "Mr. K.J. Dhage",
      ),
      Assignment(
        id: "ASN-060",
        studentId: "STU-060",
        locationId: "LOC-09",
        supervisorId: "",
        workDescription: "- Maintain discipline and silence in the Lab. - Update the systems and keep it in working condition. - Installation as per the guidance. - Keep record of students using internet.",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 16, minutes: 0),
            end: Duration(hours: 18, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Civil Lab",
        supervisorName: "Not assigned",
      ),
      Assignment(
        id: "ASN-061",
        studentId: "STU-061",
        locationId: "LOC-10",
        supervisorId: "SV-08",
        workDescription: "Complete the task given by SDO from time to time. Record keeping, Preaparing Database, Emailing etc.",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 16, minutes: 0),
            end: Duration(hours: 17, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "SDO",
        supervisorName: "Prof. R.S. Pawase",
      ),
      Assignment(
        id: "ASN-062",
        studentId: "STU-062",
        locationId: "LOC-11",
        supervisorId: "SV-06",
        workDescription: "- Maintain Clenliness at Guest house. - Assign Rooms to guest as per req. - Maintain all records of guest house. - Do the work as per direction of Mr. Khule.",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 17, minutes: 0),
            end: Duration(hours: 20, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Gymkhana",
        supervisorName: "Mr. B.S. Shinde",
      ),
      Assignment(
        id: "ASN-063",
        studentId: "STU-063",
        locationId: "LOC-11",
        supervisorId: "SV-06",
        workDescription: "- Maintain Clenliness at Guest house. - Assign Rooms to guest as per req. - Maintain all records of guest house. - Do the work as per direction of Mr. Khule.",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 16, minutes: 0),
            end: Duration(hours: 19, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Gymkhana",
        supervisorName: "Mr. B.S. Shinde",
      ),
      Assignment(
        id: "ASN-064",
        studentId: "STU-064",
        locationId: "LOC-12",
        supervisorId: "",
        workDescription: "General duty at Dispensary",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 17, minutes: 0),
            end: Duration(hours: 20, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Dispensary",
        supervisorName: "Not assigned",
      ),
      Assignment(
        id: "ASN-065",
        studentId: "STU-065",
        locationId: "LOC-13",
        supervisorId: "",
        workDescription: "General duty at Incubation",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 16, minutes: 0),
            end: Duration(hours: 18, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Incubation",
        supervisorName: "Not assigned",
      ),
      Assignment(
        id: "ASN-066",
        studentId: "STU-066",
        locationId: "LOC-13",
        supervisorId: "",
        workDescription: "General duty at Incubation",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 16, minutes: 0),
            end: Duration(hours: 18, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Incubation",
        supervisorName: "Not assigned",
      ),
      Assignment(
        id: "ASN-067",
        studentId: "STU-067",
        locationId: "LOC-14",
        supervisorId: "SV-07",
        workDescription: "- Maintain Clenliness at Guest house. - Assign Rooms to guest as per req. - Maintain all records of guest house. - Do the work as per direction of Mr. Khule.",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 18, minutes: 0),
            end: Duration(hours: 21, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "Guest House",
        supervisorName: "Mr. Khule",
      ),
      Assignment(
        id: "ASN-068",
        studentId: "STU-068",
        locationId: "LOC-15",
        supervisorId: "SV-09",
        workDescription: "Complete the task given by TPO from time to time. Record keeping, Preaparing Database, Emailing etc.",
        shiftWindows: const [
          ShiftWindow(
            start: Duration(hours: 16, minutes: 0),
            end: Duration(hours: 18, minutes: 0),
          ),
        ],
        effectiveFrom: startOfMonth,
        status: AssignmentStatus.active,
        locationName: "TPO Office",
        supervisorName: "Prof. Pravin Wakchaure",
      ),
    ];
  }
}
