"use strict";

/**
 * Canonical flag vocabulary for attendance evidence, samples and sessions.
 *
 * Flags are evidence/review signals, never automatic accusations. They are
 * written server-side only; clients may render them but never author them.
 */

const Flags = Object.freeze({
  LOCATION_REQUIRED: "LOCATION_REQUIRED",
  LOCATION_OUTSIDE_ZONE: "LOCATION_OUTSIDE_ZONE",
  LOCATION_STALE: "LOCATION_STALE",
  LOCATION_LOW_ACCURACY: "LOCATION_LOW_ACCURACY",
  IDENTITY_REQUIRED: "IDENTITY_REQUIRED",
  IDENTITY_FAILED: "IDENTITY_FAILED",
  DUPLICATE_SESSION: "DUPLICATE_SESSION",
  OVERLAPPING_SESSION: "OVERLAPPING_SESSION",
  IMPOSSIBLE_MOVEMENT: "IMPOSSIBLE_MOVEMENT",
  EARLY_CHECKOUT: "EARLY_CHECKOUT",
  MISSED_CHECKOUT: "MISSED_CHECKOUT",
  MANUAL_ADJUSTMENT: "MANUAL_ADJUSTMENT",
  INVALID_ASSIGNMENT: "INVALID_ASSIGNMENT",
  INVALID_LOCATION: "INVALID_LOCATION",
  INCONSISTENT_VERIFICATION: "INCONSISTENT_VERIFICATION",
  IMPOSSIBLE_DURATION: "IMPOSSIBLE_DURATION",
});

module.exports = { Flags };